# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param project.vivado.isBlockSynthRun true
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/floran/Vivado/aivotta/aivotta.cache/wt [current_project]
set_property parent.project_path /home/floran/Vivado/aivotta/aivotta.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo /home/floran/Vivado/aivotta/aivotta.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/add.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/util_pkg.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/add_and_eq_gt_gtu_ior_shl_shr_shru_sub_sxhw_sxqw_xor.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/add_mul_sub.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/tce_util_pkg.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/platform/almaif_axi_expander.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/platform/almaif_decoder.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/platform/almaif_mc_arbiter.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/axi4_master.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/block_copier_fu.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/platform/registers-pkg.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/platform/dbregbank.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/platform/dbsm-entity.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/platform/dbsm-rtl.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/platform/debugger.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/tta_core_imem_mau_pkg.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/tta_core_globals_pkg.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/gcu_ic/gcu_opcodes_pkg.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/gcu_ic/decoder.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/dual_port_fifo.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/fu_fma_act.vhd
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/fu_vops.vhd
  /home/floran/Documents/TCE/aivotta/proge-output/gcu_ic/ic.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/gcu_ic/idecompressor.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/gcu_ic/ifetch.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/gcu_ic/input_mux_1.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/gcu_ic/input_mux_11.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/gcu_ic/input_mux_2.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/gcu_ic/input_mux_3.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/gcu_ic/input_mux_4.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/gcu_ic/input_mux_7.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/gcu_ic/input_mux_8.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/platform/membus_splitter.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/rf_1wr_1rd_always_1_guarded_0.vhd
  /home/floran/Documents/TCE/aivotta/proge-output/platform/tta-axislave.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/platform/tta-accel.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/tta_core_params_pkg.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/tta_core.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/platform/tta_core_toplevel_params_pkg.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/vhdl/vec_lsu_1024_2.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/platform/xilinx_dp_blockram.vhdl
  /home/floran/Documents/TCE/aivotta/proge-output/platform/tta_core_toplevel.vhdl
}
read_ip -quiet /home/floran/Vivado/aivotta/aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/floran/Vivado/aivotta/aivotta.runs/toplevel_tta_core_toplevel_0_0_synth_1 -new_name toplevel_tta_core_toplevel_0_0 -ip [get_ips toplevel_tta_core_toplevel_0_0]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top toplevel_tta_core_toplevel_0_0 -part xc7z020clg400-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix toplevel_tta_core_toplevel_0_0_ toplevel_tta_core_toplevel_0_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ toplevel_tta_core_toplevel_0_0_stub.v
 lappend ipCachedFiles toplevel_tta_core_toplevel_0_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ toplevel_tta_core_toplevel_0_0_stub.vhdl
 lappend ipCachedFiles toplevel_tta_core_toplevel_0_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ toplevel_tta_core_toplevel_0_0_sim_netlist.v
 lappend ipCachedFiles toplevel_tta_core_toplevel_0_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ toplevel_tta_core_toplevel_0_0_sim_netlist.vhdl
 lappend ipCachedFiles toplevel_tta_core_toplevel_0_0_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp toplevel_tta_core_toplevel_0_0.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips toplevel_tta_core_toplevel_0_0]
}

rename_ref -prefix_all toplevel_tta_core_toplevel_0_0_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef toplevel_tta_core_toplevel_0_0.dcp
create_report "toplevel_tta_core_toplevel_0_0_synth_1_synth_report_utilization_0" "report_utilization -file toplevel_tta_core_toplevel_0_0_utilization_synth.rpt -pb toplevel_tta_core_toplevel_0_0_utilization_synth.pb"

if { [catch {
  file copy -force /home/floran/Vivado/aivotta/aivotta.runs/toplevel_tta_core_toplevel_0_0_synth_1/toplevel_tta_core_toplevel_0_0.dcp /home/floran/Vivado/aivotta/aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/floran/Vivado/aivotta/aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/floran/Vivado/aivotta/aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/floran/Vivado/aivotta/aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/floran/Vivado/aivotta/aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/floran/Vivado/aivotta/aivotta.runs/toplevel_tta_core_toplevel_0_0_synth_1/toplevel_tta_core_toplevel_0_0.dcp /home/floran/Vivado/aivotta/aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/floran/Vivado/aivotta/aivotta.runs/toplevel_tta_core_toplevel_0_0_synth_1/toplevel_tta_core_toplevel_0_0_stub.v /home/floran/Vivado/aivotta/aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/floran/Vivado/aivotta/aivotta.runs/toplevel_tta_core_toplevel_0_0_synth_1/toplevel_tta_core_toplevel_0_0_stub.vhdl /home/floran/Vivado/aivotta/aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/floran/Vivado/aivotta/aivotta.runs/toplevel_tta_core_toplevel_0_0_synth_1/toplevel_tta_core_toplevel_0_0_sim_netlist.v /home/floran/Vivado/aivotta/aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/floran/Vivado/aivotta/aivotta.runs/toplevel_tta_core_toplevel_0_0_synth_1/toplevel_tta_core_toplevel_0_0_sim_netlist.vhdl /home/floran/Vivado/aivotta/aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/floran/Vivado/aivotta/aivotta.ip_user_files/ip/toplevel_tta_core_toplevel_0_0]} {
  catch { 
    file copy -force /home/floran/Vivado/aivotta/aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0_stub.v /home/floran/Vivado/aivotta/aivotta.ip_user_files/ip/toplevel_tta_core_toplevel_0_0
  }
}

if {[file isdir /home/floran/Vivado/aivotta/aivotta.ip_user_files/ip/toplevel_tta_core_toplevel_0_0]} {
  catch { 
    file copy -force /home/floran/Vivado/aivotta/aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0_stub.vhdl /home/floran/Vivado/aivotta/aivotta.ip_user_files/ip/toplevel_tta_core_toplevel_0_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
