# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/toplevel/toplevel.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==toplevel || ORIG_REF_NAME==toplevel} -quiet] -quiet

# IP: bd/toplevel/ip/toplevel_processing_system7_0_0_1/toplevel_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==toplevel_processing_system7_0_0 || ORIG_REF_NAME==toplevel_processing_system7_0_0} -quiet] -quiet

# IP: bd/toplevel/ip/toplevel_tta_core_toplevel_0_0_1/toplevel_tta_core_toplevel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==toplevel_tta_core_toplevel_0_0 || ORIG_REF_NAME==toplevel_tta_core_toplevel_0_0} -quiet] -quiet

# IP: bd/toplevel/ip/toplevel_axi_smc_0_1/toplevel_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==toplevel_axi_smc_0 || ORIG_REF_NAME==toplevel_axi_smc_0} -quiet] -quiet

# IP: bd/toplevel/ip/toplevel_rst_ps7_0_100M_0_1/toplevel_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==toplevel_rst_ps7_0_100M_0 || ORIG_REF_NAME==toplevel_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/toplevel/ip/toplevel_axi_smc_1_0/toplevel_axi_smc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==toplevel_axi_smc_1_0 || ORIG_REF_NAME==toplevel_axi_smc_1_0} -quiet] -quiet

# XDC: bd/toplevel/toplevel_ooc.xdc
