#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Jul 28 20:59:07 CEST 2019
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto 07cabcc0346f4a5a85228754198c7d93 --incr --debug typical --relax --mt 8 --include "../../../../aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_axi_smc_0_1/bd_0/ip/ip_0/sysc" --include "../../../../aivotta.srcs/sources_1/bd/toplevel/ip/toplevel_axi_smc_0_1/bd_0/ip/ip_0/sim" -L xil_defaultlib -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tta_almaif_tb_behav xil_defaultlib.tta_almaif_tb xil_defaultlib.glbl -log elaborate.log
