-- Module generated by TTA Codesign Environment
-- 
-- Generated on Thu Jul 18 12:56:50 2019
-- 
-- Function Unit: vALU
-- 
-- Operations:
--  ge32x32to32x1        :  0
--  geu16x32to32x1       :  1
--  insertelem16x32      :  2
--  insertelem32x32      :  3
--  mac16x32to32x32      :  4
--  max16x32             :  5
--  shlsame16x32         :  6
--  shlsame32x32         :  7
--  truncwh32x32         :  8
--  vreduce32x32         :  9
--  xnorpopcountacc32x32 : 10
-- 

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.std_logic_misc.all;

entity fu_valu is
  port (
    clk : in std_logic;
    rstx : in std_logic;
    glock_in : in std_logic;
    glockreq_out : out std_logic;
    operation_in : in std_logic_vector(4-1 downto 0);
    data_in1t_in : in std_logic_vector(1024-1 downto 0);
    load_in1t_in : in std_logic;
    data_in2_in : in std_logic_vector(1024-1 downto 0);
    load_in2_in : in std_logic;
    data_in3_in : in std_logic_vector(1024-1 downto 0);
    load_in3_in : in std_logic;
    data_out1_out : out std_logic_vector(32-1 downto 0);
    data_out3_out : out std_logic_vector(1024-1 downto 0));
end entity fu_valu;

architecture rtl of fu_valu is

  constant op_ge32x32to32x1_c : std_logic_vector(3 downto 0) := "0000";
  constant op_geu16x32to32x1_c : std_logic_vector(3 downto 0) := "0001";
  constant op_insertelem16x32_c : std_logic_vector(3 downto 0) := "0010";
  constant op_insertelem32x32_c : std_logic_vector(3 downto 0) := "0011";
  constant op_mac16x32to32x32_c : std_logic_vector(3 downto 0) := "0100";
  constant op_max16x32_c : std_logic_vector(3 downto 0) := "0101";
  constant op_shlsame16x32_c : std_logic_vector(3 downto 0) := "0110";
  constant op_shlsame32x32_c : std_logic_vector(3 downto 0) := "0111";
  constant op_truncwh32x32_c : std_logic_vector(3 downto 0) := "1000";
  constant op_vreduce32x32_c : std_logic_vector(3 downto 0) := "1001";
  constant op_xnorpopcountacc32x32_c : std_logic_vector(3 downto 0) := "1010";

  signal operation : std_logic_vector(3 downto 0);
  signal data_in1t : std_logic_vector(1023 downto 0);
  signal data_in2 : std_logic_vector(1023 downto 0);
  signal data_in3 : std_logic_vector(1023 downto 0);
  signal ge32x32to32x1_op1 : std_logic_vector(1023 downto 0);
  signal ge32x32to32x1_op2 : std_logic_vector(1023 downto 0);
  signal ge32x32to32x1_op3 : std_logic_vector(31 downto 0);
  signal geu16x32to32x1_op1 : std_logic_vector(511 downto 0);
  signal geu16x32to32x1_op2 : std_logic_vector(511 downto 0);
  signal geu16x32to32x1_op3 : std_logic_vector(31 downto 0);
  signal insertelem16x32_op1 : std_logic_vector(511 downto 0);
  signal insertelem16x32_op2 : std_logic_vector(15 downto 0);
  signal insertelem16x32_op3 : std_logic_vector(31 downto 0);
  signal insertelem16x32_op4 : std_logic_vector(511 downto 0);
  signal insertelem32x32_op1 : std_logic_vector(1023 downto 0);
  signal insertelem32x32_op2 : std_logic_vector(31 downto 0);
  signal insertelem32x32_op3 : std_logic_vector(31 downto 0);
  signal insertelem32x32_op4 : std_logic_vector(1023 downto 0);
  signal mac16x32to32x32_op1 : std_logic_vector(511 downto 0);
  signal mac16x32to32x32_op2 : std_logic_vector(511 downto 0);
  signal mac16x32to32x32_op3 : std_logic_vector(1023 downto 0);
  signal mac16x32to32x32_op4 : std_logic_vector(1023 downto 0);
  signal max16x32_op1 : std_logic_vector(511 downto 0);
  signal max16x32_op2 : std_logic_vector(511 downto 0);
  signal max16x32_op3 : std_logic_vector(511 downto 0);
  signal shlsame16x32_op1 : std_logic_vector(511 downto 0);
  signal shlsame16x32_op2 : std_logic_vector(15 downto 0);
  signal shlsame16x32_op3 : std_logic_vector(511 downto 0);
  signal shlsame32x32_op1 : std_logic_vector(1023 downto 0);
  signal shlsame32x32_op2 : std_logic_vector(31 downto 0);
  signal shlsame32x32_op3 : std_logic_vector(1023 downto 0);
  signal truncwh32x32_op1 : std_logic_vector(1023 downto 0);
  signal truncwh32x32_op2 : std_logic_vector(511 downto 0);
  signal vreduce32x32_op1 : std_logic_vector(1023 downto 0);
  signal vreduce32x32_op2 : std_logic_vector(31 downto 0);
  signal xnorpopcountacc32x32_op1 : std_logic_vector(1023 downto 0);
  signal xnorpopcountacc32x32_op2 : std_logic_vector(1023 downto 0);
  signal xnorpopcountacc32x32_op3 : std_logic_vector(511 downto 0);
  signal xnorpopcountacc32x32_op4 : std_logic_vector(511 downto 0);
  signal operation_ge32x32to32x1_cycle_0_trigger : std_logic;
  signal operation_geu16x32to32x1_cycle_0_trigger : std_logic;
  signal operation_insertelem16x32_cycle_0_trigger : std_logic;
  signal operation_insertelem32x32_cycle_0_trigger : std_logic;
  signal operation_mac16x32to32x32_cycle_0_trigger : std_logic;
  signal operation_max16x32_cycle_0_trigger : std_logic;
  signal operation_shlsame16x32_cycle_0_trigger : std_logic;
  signal operation_shlsame32x32_cycle_0_trigger : std_logic;
  signal operation_truncwh32x32_cycle_0_trigger : std_logic;
  signal operation_vreduce32x32_cycle_0_trigger : std_logic;
  signal operation_xnorpopcountacc32x32_cycle_0_trigger : std_logic;
  signal operation_0_r : std_logic_vector(3 downto 0);

  signal shadow_in2_r : std_logic_vector(1023 downto 0);
  signal shadow_in3_r : std_logic_vector(1023 downto 0);
  signal data_out1_cycle_0_r : std_logic_vector(31 downto 0);
  signal data_out3_cycle_0_r : std_logic_vector(1023 downto 0);

begin

  operation <= operation_in;
  data_in1t <= data_in1t_in;

  shadow_in2_sp : process(clk, rstx)
  begin
    if rstx = '0' then
      shadow_in2_r <= (others => '0');
    elsif clk = '1' and clk'event then
      if ((glock_in = '0') and (load_in2_in = '1')) then
        shadow_in2_r <= data_in2_in;
      end if;
    end if;
  end process shadow_in2_sp;

  shadow_in2_cp : process(shadow_in2_r, load_in1t_in, data_in2_in, load_in2_in)
  begin
    if ((load_in1t_in = '1') and (load_in2_in = '1')) then
      data_in2 <= data_in2_in;
    else
      data_in2 <= shadow_in2_r;
    end if;
  end process shadow_in2_cp;

  shadow_in3_sp : process(clk, rstx)
  begin
    if rstx = '0' then
      shadow_in3_r <= (others => '0');
    elsif clk = '1' and clk'event then
      if ((glock_in = '0') and (load_in3_in = '1')) then
        shadow_in3_r <= data_in3_in;
      end if;
    end if;
  end process shadow_in3_sp;

  shadow_in3_cp : process(shadow_in3_r, data_in3_in, load_in1t_in, load_in3_in)
  begin
    if ((load_in1t_in = '1') and (load_in3_in = '1')) then
      data_in3 <= data_in3_in;
    else
      data_in3 <= shadow_in3_r;
    end if;
  end process shadow_in3_cp;

  ge32x32to32x1_op1 <= data_in3(1023 downto 0);
  ge32x32to32x1_op2 <= data_in1t(1023 downto 0);
  geu16x32to32x1_op1 <= data_in1t(511 downto 0);
  geu16x32to32x1_op2 <= data_in2(511 downto 0);
  insertelem16x32_op1 <= data_in1t(511 downto 0);
  insertelem16x32_op2 <= data_in3(15 downto 0);
  insertelem16x32_op3 <= data_in2(31 downto 0);
  insertelem32x32_op1 <= data_in1t(1023 downto 0);
  insertelem32x32_op2 <= data_in3(31 downto 0);
  insertelem32x32_op3 <= data_in2(31 downto 0);
  mac16x32to32x32_op1 <= data_in1t(511 downto 0);
  mac16x32to32x32_op2 <= data_in2(511 downto 0);
  mac16x32to32x32_op3 <= data_in3(1023 downto 0);
  max16x32_op1 <= data_in3(511 downto 0);
  max16x32_op2 <= data_in1t(511 downto 0);
  shlsame16x32_op1 <= data_in1t(511 downto 0);
  shlsame16x32_op2 <= data_in3(15 downto 0);
  shlsame32x32_op1 <= data_in1t(1023 downto 0);
  shlsame32x32_op2 <= data_in3(31 downto 0);
  truncwh32x32_op1 <= data_in1t(1023 downto 0);
  vreduce32x32_op1 <= data_in1t(1023 downto 0);
  xnorpopcountacc32x32_op1 <= data_in2(1023 downto 0);
  xnorpopcountacc32x32_op2 <= data_in1t(1023 downto 0);
  xnorpopcountacc32x32_op3 <= data_in3(511 downto 0);
  operation_0_r <= operation_in;

  operations_actual_cp : process(xnorpopcountacc32x32_op2, insertelem32x32_op1, vreduce32x32_op1, insertelem32x32_op2, insertelem32x32_op3, insertelem16x32_op1, load_in1t_in, geu16x32to32x1_op1, mac16x32to32x32_op3, max16x32_op2, insertelem16x32_op2, xnorpopcountacc32x32_op1, geu16x32to32x1_op2, insertelem16x32_op3, mac16x32to32x32_op1, mac16x32to32x32_op2, operation_0_r, xnorpopcountacc32x32_op3, max16x32_op1, shlsame16x32_op1, shlsame16x32_op2, shlsame32x32_op1, truncwh32x32_op1, ge32x32to32x1_op1, ge32x32to32x1_op2, shlsame32x32_op2)
    variable mac16x32to32x32_a : signed(16-1 downto 0);
    variable mac16x32to32x32_b : signed(16-1 downto 0);
    variable mac16x32to32x32_c : signed(32-1 downto 0);
    variable mac16x32to32x32_mul : signed(32-1 downto 0);
    variable mac16x32to32x32_out_v : signed(32-1 downto 0);
    variable mac16x32to32x32_result : std_logic_vector(1024-1 downto 0);
    variable shlsame32x32_result : std_logic_vector(1024-1 downto 0);
    variable insertelem32x32_result : std_logic_vector(1024-1 downto 0);
    variable shlsame16x32_result : std_logic_vector(512-1 downto 0);
    variable max16x32_result : std_logic_vector(512-1 downto 0);
    variable insertelem16x32_result : std_logic_vector(512-1 downto 0);
    variable xnorpopcountacc32x32_a : unsigned(32-1 downto 0);
    variable xnorpopcountacc32x32_b : unsigned(32-1 downto 0);
    variable xnorpopcountacc32x32_count : unsigned(16-1 downto 0);
    variable xnorpopcountacc32x32_xnor_result : unsigned(32-1 downto 0);
    variable xnorpopcountacc32x32_result : std_logic_vector(512-1 downto 0);
    variable ge32x32to32x1_result : std_logic_vector(32-1 downto 0);
    variable truncwh32x32_result : std_logic_vector(512-1 downto 0);
    variable vreduce32x32_sum : signed(32-1 downto 0);
    variable geu16x32to32x1_result : std_logic_vector(32-1 downto 0);
  begin
    operation_ge32x32to32x1_cycle_0_trigger <= '0';
    ge32x32to32x1_result := (others => '-');
    ge32x32to32x1_result := (others => '-');
    ge32x32to32x1_op3 <= (others => '-');
    ge32x32to32x1_result := (others => '-');
    operation_geu16x32to32x1_cycle_0_trigger <= '0';
    geu16x32to32x1_result := (others => '-');
    geu16x32to32x1_result := (others => '-');
    geu16x32to32x1_op3 <= (others => '-');
    geu16x32to32x1_result := (others => '-');
    operation_insertelem16x32_cycle_0_trigger <= '0';
    insertelem16x32_result := (others => '-');
    insertelem16x32_result := (others => '-');
    insertelem16x32_op4 <= (others => '-');
    insertelem16x32_result := (others => '-');
    operation_insertelem32x32_cycle_0_trigger <= '0';
    insertelem32x32_result := (others => '-');
    insertelem32x32_result := (others => '-');
    insertelem32x32_op4 <= (others => '-');
    insertelem32x32_result := (others => '-');
    operation_mac16x32to32x32_cycle_0_trigger <= '0';
    mac16x32to32x32_a := (others => '-');
    mac16x32to32x32_b := (others => '-');
    mac16x32to32x32_c := (others => '-');
    mac16x32to32x32_a := (others => '-');
    mac16x32to32x32_b := (others => '-');
    mac16x32to32x32_mul := (others => '-');
    mac16x32to32x32_c := (others => '-');
    mac16x32to32x32_mul := (others => '-');
    mac16x32to32x32_out_v := (others => '-');
    mac16x32to32x32_out_v := (others => '-');
    mac16x32to32x32_result := (others => '-');
    mac16x32to32x32_op4 <= (others => '-');
    mac16x32to32x32_result := (others => '-');
    operation_max16x32_cycle_0_trigger <= '0';
    max16x32_result := (others => '-');
    max16x32_result := (others => '-');
    max16x32_op3 <= (others => '-');
    max16x32_result := (others => '-');
    operation_shlsame16x32_cycle_0_trigger <= '0';
    shlsame16x32_result := (others => '-');
    shlsame16x32_op3 <= (others => '-');
    shlsame16x32_result := (others => '-');
    operation_shlsame32x32_cycle_0_trigger <= '0';
    shlsame32x32_result := (others => '-');
    shlsame32x32_op3 <= (others => '-');
    shlsame32x32_result := (others => '-');
    operation_truncwh32x32_cycle_0_trigger <= '0';
    truncwh32x32_result := (others => '-');
    truncwh32x32_op2 <= (others => '-');
    truncwh32x32_result := (others => '-');
    operation_vreduce32x32_cycle_0_trigger <= '0';
    vreduce32x32_sum := (others => '-');
    vreduce32x32_sum := (others => '-');
    vreduce32x32_op2 <= (others => '-');
    vreduce32x32_sum := (others => '-');
    operation_xnorpopcountacc32x32_cycle_0_trigger <= '0';
    xnorpopcountacc32x32_a := (others => '-');
    xnorpopcountacc32x32_b := (others => '-');
    xnorpopcountacc32x32_count := (others => '-');
    xnorpopcountacc32x32_a := (others => '-');
    xnorpopcountacc32x32_b := (others => '-');
    xnorpopcountacc32x32_xnor_result := (others => '-');
    xnorpopcountacc32x32_xnor_result := (others => '-');
    xnorpopcountacc32x32_count := (others => '-');
    xnorpopcountacc32x32_count := (others => '-');
    xnorpopcountacc32x32_result := (others => '-');
    xnorpopcountacc32x32_op4 <= (others => '-');
    xnorpopcountacc32x32_result := (others => '-');
    if (load_in1t_in = '1') then
      case operation_0_r is
        when op_ge32x32to32x1_c =>
          for i in 0 to 31 loop
            if signed(ge32x32to32x1_op1((i+1)*32-1 downto i*32)) >= signed(ge32x32to32x1_op2((i+1)*32-1 downto i*32)) then
              ge32x32to32x1_result(i) := '1';
            else
              ge32x32to32x1_result(i) := '0';
            end if;
          end loop;
          ge32x32to32x1_op3 <= ge32x32to32x1_result;
          operation_ge32x32to32x1_cycle_0_trigger <= load_in1t_in;
        when op_geu16x32to32x1_c =>
          for i in 0 to 31 loop
            if unsigned(geu16x32to32x1_op1((i+1)*16-1 downto i*16)) >= unsigned(geu16x32to32x1_op2((i+1)*16-1 downto i*16)) then
              geu16x32to32x1_result(i) := '1';
            else
              geu16x32to32x1_result(i) := '0';
            end if;
          end loop;
          geu16x32to32x1_op3 <= geu16x32to32x1_result;
          operation_geu16x32to32x1_cycle_0_trigger <= load_in1t_in;
        when op_insertelem16x32_c =>
          for i in 0 to 31 loop
            if(i = to_integer(unsigned(insertelem16x32_op3))) then
              insertelem16x32_result((i+1)*16-1 downto i*16) := insertelem16x32_op2;
            else
              insertelem16x32_result((i+1)*16-1 downto i*16) := insertelem16x32_op1((i+1)*16-1 downto i*16);
            end if;
          end loop;
          insertelem16x32_op4 <= insertelem16x32_result;
          operation_insertelem16x32_cycle_0_trigger <= load_in1t_in;
        when op_insertelem32x32_c =>
          for i in 0 to 31 loop
            if(i = to_integer(unsigned(insertelem32x32_op3))) then
              insertelem32x32_result((i+1)*32-1 downto i*32) := insertelem32x32_op2;
            else
              insertelem32x32_result((i+1)*32-1 downto i*32) := insertelem32x32_op1((i+1)*32-1 downto i*32);
            end if;
          end loop;
          insertelem32x32_op4 <= insertelem32x32_result;
          operation_insertelem32x32_cycle_0_trigger <= load_in1t_in;
        when op_mac16x32to32x32_c =>
          for i in 0 to 31 loop
            mac16x32to32x32_a                         := signed(mac16x32to32x32_op1((i+1)*16-1 downto i*16));
            mac16x32to32x32_b                         := signed(mac16x32to32x32_op2((i+1)*16-1 downto i*16));
            mac16x32to32x32_c                         := signed(mac16x32to32x32_op3((i+1)*32-1 downto i*32));
            mac16x32to32x32_mul                       := mac16x32to32x32_a * mac16x32to32x32_b;
            mac16x32to32x32_out_v                       := mac16x32to32x32_c + mac16x32to32x32_mul;
            mac16x32to32x32_result((i+1)*32-1 downto i*32) := std_logic_vector(mac16x32to32x32_out_v);
          end loop;
          mac16x32to32x32_op4 <= mac16x32to32x32_result;
          operation_mac16x32to32x32_cycle_0_trigger <= load_in1t_in;
        when op_max16x32_c =>
          for i in 0 to 31 loop
            if signed(max16x32_op1((i+1)*16-1 downto i*16)) > signed(max16x32_op2((i+1)*16-1 downto i*16)) then
              max16x32_result((i+1)*16-1 downto i*16) := max16x32_op1((i+1)*16-1 downto i*16);
            else
              max16x32_result((i+1)*16-1 downto i*16) := max16x32_op2((i+1)*16-1 downto i*16);
            end if;
          end loop;
          max16x32_op3 <= max16x32_result;
          operation_max16x32_cycle_0_trigger <= load_in1t_in;
        when op_shlsame16x32_c =>
          for i in 0 to 31 loop
            shlsame16x32_result((i+1)*16-1 downto i*16) := std_logic_vector(shift_left(unsigned(shlsame16x32_op1((i+1)*16-1 downto i*16)), to_integer(unsigned(shlsame16x32_op2))));
          end loop;
          shlsame16x32_op3 <= shlsame16x32_result;
          operation_shlsame16x32_cycle_0_trigger <= load_in1t_in;
        when op_shlsame32x32_c =>
          for i in 0 to 31 loop
            shlsame32x32_result((i+1)*32-1 downto i*32) := std_logic_vector(shift_left(unsigned(shlsame32x32_op1((i+1)*32-1 downto i*32)), to_integer(unsigned(shlsame32x32_op2))));
          end loop;
          shlsame32x32_op3 <= shlsame32x32_result;
          operation_shlsame32x32_cycle_0_trigger <= load_in1t_in;
        when op_truncwh32x32_c =>
          for i in 0 to 31 loop
            truncwh32x32_result((i+1)*16-1 downto i*16) := truncwh32x32_op1((i+1)*32-17 downto i*32);
          end loop;
          truncwh32x32_op2 <= truncwh32x32_result;
          operation_truncwh32x32_cycle_0_trigger <= load_in1t_in;
        when op_vreduce32x32_c =>
          for i in 0 to 31 loop
            if (i = 0) then
              vreduce32x32_sum := signed(vreduce32x32_op1((i+1)*32-1 downto i*32));  
            else
              vreduce32x32_sum := vreduce32x32_sum + signed(vreduce32x32_op1((i+1)*32-1 downto i*32));
            end if;
          end loop;
          vreduce32x32_op2 <= std_logic_vector(vreduce32x32_sum);
          operation_vreduce32x32_cycle_0_trigger <= load_in1t_in;
        when op_xnorpopcountacc32x32_c =>
          for i in 0 to 31 loop
            xnorpopcountacc32x32_a                         := unsigned(xnorpopcountacc32x32_op1((i+1)*32-1 downto i*32));
            xnorpopcountacc32x32_b                         := unsigned(xnorpopcountacc32x32_op2((i+1)*32-1 downto i*32));
            xnorpopcountacc32x32_count                     := unsigned(xnorpopcountacc32x32_op3((i+1)*16-1 downto i*16));
            xnorpopcountacc32x32_xnor_result               := xnorpopcountacc32x32_a xnor xnorpopcountacc32x32_b;
            for j in 0 to 31 loop
              if(xnorpopcountacc32x32_xnor_result(j) = '1') then
                xnorpopcountacc32x32_count := xnorpopcountacc32x32_count + 1;
              end if;
            end loop;
            
            xnorpopcountacc32x32_result((i+1)*16-1 downto i*16) := std_logic_vector(xnorpopcountacc32x32_count);
          end loop;
          xnorpopcountacc32x32_op4 <= xnorpopcountacc32x32_result;
          operation_xnorpopcountacc32x32_cycle_0_trigger <= load_in1t_in;
        when others =>
      end case;
    end if;
  end process operations_actual_cp;

  operations_cycle_0_sp : process(clk, rstx)
  begin
    if rstx = '0' then
      data_out3_cycle_0_r <= (others => '0');
      data_out1_cycle_0_r <= (others => '0');
    elsif clk = '1' and clk'event then
      if (glock_in = '0') then
        if (operation_ge32x32to32x1_cycle_0_trigger = '1') then
          data_out1_cycle_0_r <= ge32x32to32x1_op3;
        end if;
        if (operation_geu16x32to32x1_cycle_0_trigger = '1') then
          data_out1_cycle_0_r <= geu16x32to32x1_op3;
        end if;
        if (operation_insertelem16x32_cycle_0_trigger = '1') then
          data_out3_cycle_0_r <= ((1024-1 downto 512 => '0') & insertelem16x32_op4);
        end if;
        if (operation_insertelem32x32_cycle_0_trigger = '1') then
          data_out3_cycle_0_r <= insertelem32x32_op4;
        end if;
        if (operation_mac16x32to32x32_cycle_0_trigger = '1') then
          data_out3_cycle_0_r <= mac16x32to32x32_op4;
        end if;
        if (operation_max16x32_cycle_0_trigger = '1') then
          data_out3_cycle_0_r <= ((1024-1 downto 512 => '0') & max16x32_op3);
        end if;
        if (operation_shlsame16x32_cycle_0_trigger = '1') then
          data_out3_cycle_0_r <= ((1024-1 downto 512 => '0') & shlsame16x32_op3);
        end if;
        if (operation_shlsame32x32_cycle_0_trigger = '1') then
          data_out3_cycle_0_r <= shlsame32x32_op3;
        end if;
        if (operation_truncwh32x32_cycle_0_trigger = '1') then
          data_out3_cycle_0_r <= ((1024-1 downto 512 => '0') & truncwh32x32_op2);
        end if;
        if (operation_vreduce32x32_cycle_0_trigger = '1') then
          data_out1_cycle_0_r <= vreduce32x32_op2;
        end if;
        if (operation_xnorpopcountacc32x32_cycle_0_trigger = '1') then
          data_out3_cycle_0_r <= ((1024-1 downto 512 => '0') & xnorpopcountacc32x32_op4);
        end if;
      end if;
    end if;
  end process operations_cycle_0_sp;

  data_out1_out <= data_out1_cycle_0_r;
  data_out3_out <= data_out3_cycle_0_r;
  glockreq_out <= '0';

end architecture rtl;

